# Create ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imc-edge-docker
  namespace: imc-edge-prod
  labels:
    app.kubernetes.io/name: imc-edge-docker
    app.kubernetes.io/instance: imc-edge-instance
---
# Create PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: imc-edge-data
  namespace: imc-edge-prod
  labels:
    app.kubernetes.io/name: imc-edge-docker
    app.kubernetes.io/instance: imc-edge-instance
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10G"
---
# Create Service
apiVersion: v1
kind: Service
metadata:
  name: imc-edge-docker
  namespace: imc-edge-prod
  labels:
    app.kubernetes.io/name: imc-edge-docker
    app.kubernetes.io/instance: imc-edge-instance
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: imc-edge-docker
    app.kubernetes.io/instance: imc-edge-instance
---
# Create Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imc-edge-docker
  namespace: imc-edge-prod
  labels:
    app.kubernetes.io/name: imc-edge-docker
    app.kubernetes.io/instance: imc-edge-instance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imc-edge-docker
      app.kubernetes.io/instance: imc-edge-instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imc-edge-docker
        app.kubernetes.io/instance: imc-edge-instance
    spec:
      serviceAccountName: imc-edge-docker
      securityContext:
        {}
      imagePullSecrets:
        - name: imc-credential
      containers:
        - name: imc-edge-docker
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          image: "us-docker.pkg.dev/litmus-customer-facing/imce-build/mce:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var
              mountPropagation: 
              name: imc-edge-data
              subPath: 
              subPathExpr: 
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 4
              memory: 4096Mi
      volumes:
        - name: imc-edge-data
          persistentVolumeClaim:
            claimName: imc-edge-data